/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as EssaiRouteImport } from './routes/essai'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EssaiIndexRouteImport } from './routes/essai.index'
import { Route as EssaiScheduleRouteImport } from './routes/essai.schedule'
import { Route as EssaiPreviewRouteImport } from './routes/essai.preview'
import { Route as EssaiImportRouteImport } from './routes/essai.import'
import { Route as EssaiAnalyseRouteImport } from './routes/essai.analyse'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated/store'
import { Route as AuthenticatedPromotionsRouteImport } from './routes/_authenticated/promotions'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedGenerateRouteImport } from './routes/_authenticated/generate'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCreationRouteImport } from './routes/_authenticated/creation'
import { Route as AuthenticatedConnectionsRouteImport } from './routes/_authenticated/connections'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedLibraryPromotionIdRouteImport } from './routes/_authenticated/library.$promotionId'
import { Route as AuthenticatedAdminTemplatesRouteImport } from './routes/_authenticated/admin.templates'
import { Route as AuthenticatedAdminPresetsRouteImport } from './routes/_authenticated/admin.presets'
import { Route as AuthenticatedAdminGraphicsRouteImport } from './routes/_authenticated/admin.graphics'
import { Route as AuthenticatedAdminFontsRouteImport } from './routes/_authenticated/admin.fonts'
import { Route as AuthenticatedAdminBrandGuidelinesRouteImport } from './routes/_authenticated/admin.brand-guidelines'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaiRoute = EssaiRouteImport.update({
  id: '/essai',
  path: '/essai',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaiIndexRoute = EssaiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EssaiRoute,
} as any)
const EssaiScheduleRoute = EssaiScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => EssaiRoute,
} as any)
const EssaiPreviewRoute = EssaiPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => EssaiRoute,
} as any)
const EssaiImportRoute = EssaiImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => EssaiRoute,
} as any)
const EssaiAnalyseRoute = EssaiAnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => EssaiRoute,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromotionsRoute = AuthenticatedPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGenerateRoute = AuthenticatedGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreationRoute = AuthenticatedCreationRouteImport.update({
  id: '/creation',
  path: '/creation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectionsRoute =
  AuthenticatedConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedLibraryPromotionIdRoute =
  AuthenticatedLibraryPromotionIdRouteImport.update({
    id: '/$promotionId',
    path: '/$promotionId',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)
const AuthenticatedAdminTemplatesRoute =
  AuthenticatedAdminTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPresetsRoute =
  AuthenticatedAdminPresetsRouteImport.update({
    id: '/presets',
    path: '/presets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGraphicsRoute =
  AuthenticatedAdminGraphicsRouteImport.update({
    id: '/graphics',
    path: '/graphics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFontsRoute = AuthenticatedAdminFontsRouteImport.update({
  id: '/fonts',
  path: '/fonts',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBrandGuidelinesRoute =
  AuthenticatedAdminBrandGuidelinesRouteImport.update({
    id: '/brand-guidelines',
    path: '/brand-guidelines',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/essai': typeof EssaiRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/creation': typeof AuthenticatedCreationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/library': typeof AuthenticatedLibraryRouteWithChildren
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/store': typeof AuthenticatedStoreRoute
  '/essai/analyse': typeof EssaiAnalyseRoute
  '/essai/import': typeof EssaiImportRoute
  '/essai/preview': typeof EssaiPreviewRoute
  '/essai/schedule': typeof EssaiScheduleRoute
  '/essai/': typeof EssaiIndexRoute
  '/admin/brand-guidelines': typeof AuthenticatedAdminBrandGuidelinesRoute
  '/admin/fonts': typeof AuthenticatedAdminFontsRoute
  '/admin/graphics': typeof AuthenticatedAdminGraphicsRoute
  '/admin/presets': typeof AuthenticatedAdminPresetsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/library/$promotionId': typeof AuthenticatedLibraryPromotionIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/creation': typeof AuthenticatedCreationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/library': typeof AuthenticatedLibraryRouteWithChildren
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/store': typeof AuthenticatedStoreRoute
  '/essai/analyse': typeof EssaiAnalyseRoute
  '/essai/import': typeof EssaiImportRoute
  '/essai/preview': typeof EssaiPreviewRoute
  '/essai/schedule': typeof EssaiScheduleRoute
  '/essai': typeof EssaiIndexRoute
  '/admin/brand-guidelines': typeof AuthenticatedAdminBrandGuidelinesRoute
  '/admin/fonts': typeof AuthenticatedAdminFontsRoute
  '/admin/graphics': typeof AuthenticatedAdminGraphicsRoute
  '/admin/presets': typeof AuthenticatedAdminPresetsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/library/$promotionId': typeof AuthenticatedLibraryPromotionIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/essai': typeof EssaiRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/connections': typeof AuthenticatedConnectionsRoute
  '/_authenticated/creation': typeof AuthenticatedCreationRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/generate': typeof AuthenticatedGenerateRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRouteWithChildren
  '/_authenticated/promotions': typeof AuthenticatedPromotionsRoute
  '/_authenticated/store': typeof AuthenticatedStoreRoute
  '/essai/analyse': typeof EssaiAnalyseRoute
  '/essai/import': typeof EssaiImportRoute
  '/essai/preview': typeof EssaiPreviewRoute
  '/essai/schedule': typeof EssaiScheduleRoute
  '/essai/': typeof EssaiIndexRoute
  '/_authenticated/admin/brand-guidelines': typeof AuthenticatedAdminBrandGuidelinesRoute
  '/_authenticated/admin/fonts': typeof AuthenticatedAdminFontsRoute
  '/_authenticated/admin/graphics': typeof AuthenticatedAdminGraphicsRoute
  '/_authenticated/admin/presets': typeof AuthenticatedAdminPresetsRoute
  '/_authenticated/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/_authenticated/library/$promotionId': typeof AuthenticatedLibraryPromotionIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/essai'
    | '/onboarding'
    | '/pricing'
    | '/sitemap.xml'
    | '/admin'
    | '/calendar'
    | '/catalog'
    | '/connections'
    | '/creation'
    | '/dashboard'
    | '/generate'
    | '/library'
    | '/promotions'
    | '/store'
    | '/essai/analyse'
    | '/essai/import'
    | '/essai/preview'
    | '/essai/schedule'
    | '/essai/'
    | '/admin/brand-guidelines'
    | '/admin/fonts'
    | '/admin/graphics'
    | '/admin/presets'
    | '/admin/templates'
    | '/library/$promotionId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/pricing'
    | '/sitemap.xml'
    | '/calendar'
    | '/catalog'
    | '/connections'
    | '/creation'
    | '/dashboard'
    | '/generate'
    | '/library'
    | '/promotions'
    | '/store'
    | '/essai/analyse'
    | '/essai/import'
    | '/essai/preview'
    | '/essai/schedule'
    | '/essai'
    | '/admin/brand-guidelines'
    | '/admin/fonts'
    | '/admin/graphics'
    | '/admin/presets'
    | '/admin/templates'
    | '/library/$promotionId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/essai'
    | '/onboarding'
    | '/pricing'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/calendar'
    | '/_authenticated/catalog'
    | '/_authenticated/connections'
    | '/_authenticated/creation'
    | '/_authenticated/dashboard'
    | '/_authenticated/generate'
    | '/_authenticated/library'
    | '/_authenticated/promotions'
    | '/_authenticated/store'
    | '/essai/analyse'
    | '/essai/import'
    | '/essai/preview'
    | '/essai/schedule'
    | '/essai/'
    | '/_authenticated/admin/brand-guidelines'
    | '/_authenticated/admin/fonts'
    | '/_authenticated/admin/graphics'
    | '/_authenticated/admin/presets'
    | '/_authenticated/admin/templates'
    | '/_authenticated/library/$promotionId'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EssaiRoute: typeof EssaiRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essai': {
      id: '/essai'
      path: '/essai'
      fullPath: '/essai'
      preLoaderRoute: typeof EssaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essai/': {
      id: '/essai/'
      path: '/'
      fullPath: '/essai/'
      preLoaderRoute: typeof EssaiIndexRouteImport
      parentRoute: typeof EssaiRoute
    }
    '/essai/schedule': {
      id: '/essai/schedule'
      path: '/schedule'
      fullPath: '/essai/schedule'
      preLoaderRoute: typeof EssaiScheduleRouteImport
      parentRoute: typeof EssaiRoute
    }
    '/essai/preview': {
      id: '/essai/preview'
      path: '/preview'
      fullPath: '/essai/preview'
      preLoaderRoute: typeof EssaiPreviewRouteImport
      parentRoute: typeof EssaiRoute
    }
    '/essai/import': {
      id: '/essai/import'
      path: '/import'
      fullPath: '/essai/import'
      preLoaderRoute: typeof EssaiImportRouteImport
      parentRoute: typeof EssaiRoute
    }
    '/essai/analyse': {
      id: '/essai/analyse'
      path: '/analyse'
      fullPath: '/essai/analyse'
      preLoaderRoute: typeof EssaiAnalyseRouteImport
      parentRoute: typeof EssaiRoute
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promotions': {
      id: '/_authenticated/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AuthenticatedPromotionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate': {
      id: '/_authenticated/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AuthenticatedGenerateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creation': {
      id: '/_authenticated/creation'
      path: '/creation'
      fullPath: '/creation'
      preLoaderRoute: typeof AuthenticatedCreationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/library/$promotionId': {
      id: '/_authenticated/library/$promotionId'
      path: '/$promotionId'
      fullPath: '/library/$promotionId'
      preLoaderRoute: typeof AuthenticatedLibraryPromotionIdRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/_authenticated/admin/templates': {
      id: '/_authenticated/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/presets': {
      id: '/_authenticated/admin/presets'
      path: '/presets'
      fullPath: '/admin/presets'
      preLoaderRoute: typeof AuthenticatedAdminPresetsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/graphics': {
      id: '/_authenticated/admin/graphics'
      path: '/graphics'
      fullPath: '/admin/graphics'
      preLoaderRoute: typeof AuthenticatedAdminGraphicsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fonts': {
      id: '/_authenticated/admin/fonts'
      path: '/fonts'
      fullPath: '/admin/fonts'
      preLoaderRoute: typeof AuthenticatedAdminFontsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/brand-guidelines': {
      id: '/_authenticated/admin/brand-guidelines'
      path: '/brand-guidelines'
      fullPath: '/admin/brand-guidelines'
      preLoaderRoute: typeof AuthenticatedAdminBrandGuidelinesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBrandGuidelinesRoute: typeof AuthenticatedAdminBrandGuidelinesRoute
  AuthenticatedAdminFontsRoute: typeof AuthenticatedAdminFontsRoute
  AuthenticatedAdminGraphicsRoute: typeof AuthenticatedAdminGraphicsRoute
  AuthenticatedAdminPresetsRoute: typeof AuthenticatedAdminPresetsRoute
  AuthenticatedAdminTemplatesRoute: typeof AuthenticatedAdminTemplatesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBrandGuidelinesRoute:
    AuthenticatedAdminBrandGuidelinesRoute,
  AuthenticatedAdminFontsRoute: AuthenticatedAdminFontsRoute,
  AuthenticatedAdminGraphicsRoute: AuthenticatedAdminGraphicsRoute,
  AuthenticatedAdminPresetsRoute: AuthenticatedAdminPresetsRoute,
  AuthenticatedAdminTemplatesRoute: AuthenticatedAdminTemplatesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedLibraryRouteChildren {
  AuthenticatedLibraryPromotionIdRoute: typeof AuthenticatedLibraryPromotionIdRoute
}

const AuthenticatedLibraryRouteChildren: AuthenticatedLibraryRouteChildren = {
  AuthenticatedLibraryPromotionIdRoute: AuthenticatedLibraryPromotionIdRoute,
}

const AuthenticatedLibraryRouteWithChildren =
  AuthenticatedLibraryRoute._addFileChildren(AuthenticatedLibraryRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedConnectionsRoute: typeof AuthenticatedConnectionsRoute
  AuthenticatedCreationRoute: typeof AuthenticatedCreationRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGenerateRoute: typeof AuthenticatedGenerateRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRouteWithChildren
  AuthenticatedPromotionsRoute: typeof AuthenticatedPromotionsRoute
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedConnectionsRoute: AuthenticatedConnectionsRoute,
  AuthenticatedCreationRoute: AuthenticatedCreationRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGenerateRoute: AuthenticatedGenerateRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRouteWithChildren,
  AuthenticatedPromotionsRoute: AuthenticatedPromotionsRoute,
  AuthenticatedStoreRoute: AuthenticatedStoreRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EssaiRouteChildren {
  EssaiAnalyseRoute: typeof EssaiAnalyseRoute
  EssaiImportRoute: typeof EssaiImportRoute
  EssaiPreviewRoute: typeof EssaiPreviewRoute
  EssaiScheduleRoute: typeof EssaiScheduleRoute
  EssaiIndexRoute: typeof EssaiIndexRoute
}

const EssaiRouteChildren: EssaiRouteChildren = {
  EssaiAnalyseRoute: EssaiAnalyseRoute,
  EssaiImportRoute: EssaiImportRoute,
  EssaiPreviewRoute: EssaiPreviewRoute,
  EssaiScheduleRoute: EssaiScheduleRoute,
  EssaiIndexRoute: EssaiIndexRoute,
}

const EssaiRouteWithChildren = EssaiRoute._addFileChildren(EssaiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EssaiRoute: EssaiRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
